### ISSUE TITLE
Strange behavior with large file(s)

### ISSUE THREAD

**Issue by freekvh** [projectsend/projectsend#1268]
Hi All,

I'm using projectsend to receive large files (currently I'm trying to test-upload an 11 GB file).

Testing with small files, things are kind of as expected. You can drag files into the Upload files section and they will be listed. To be honest it is not immediately obvious that "upload files" starts the actual upload, for a while I thought it was a button to add more files to upload. Anyway, things work. Also, the message says: "Click on Add files to select all the files that you want to upload, and then click continue." but there is no button labelled "continue". Only a button "Upload files" and "Add files".

When I drag a large file into the field, It lists the file, I click "Upload files", and then after about 10 sec I always get this message: Are you sure you want to leave the page? When I leave, the upload stops. When I stay, the upload proceeds. There is very little indication though that something is happening. The % goes up, very slowly but the size stays at 0 b:

![image](https://github.com/projectsend/projectsend/assets/12241293/feba36b6-5fc8-46c0-8b84-f2d98f2bfffc)

It does seem to work though I fear that client will be a bit puzzled as to what is going on.

I'm using Firefox btw, and the latest Linux server IO image with a Caddy reverse proxy.

Other than that, beautiful project! I also love that setting up email notifications was so hassle free (with SMTP). Thank you!

**Comment by sinag** [comment]
I have the same problem with max file set to 50gb, try to send something more than 10gb, same problem, and upload never completes btw

**Comment by bepstein111** [comment]
@freekvh Sorry that I don't have any information related to this issue, but I cannot find any information about getting projectsend working with Caddy. care to share your caddyfile? right now for some reason I have to go to use the port number even at my public url.

**Comment by freekvh** [comment]
@bepstein111 This is what I have:

In docker-compose.yaml:

```yaml
version: "3.1"
services:
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/sites:/var/www/html
      - ./caddy/caddy_data:/data
    depends_on:
      - projectsend
    restart: unless-stopped

  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    depends_on:
      - db-projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MAX_UPLOAD=20000
    volumes:
      - ./projectsend_config:/config
      - ./projectsend_data:/data
    # ports:
    #   - 127.0.0.1:8080:80
    restart: unless-stopped

  db-projectsend:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb-projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MARIADBPASSWORDPS}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=PS_database
      - MYSQL_USER=PS_dbuser
      - MYSQL_PASSWORD=${DBPASSWORDPS}
    volumes:
      - ./db-projectsend:/config
    restart: unless-stopped
```

Then in the caddyfile:

```
data.my-domain.com {
	reverse_proxy projectsend:80
}
```

(on the side, I love how simple caddy makes such an https enabled reverse proxy compared to the old days, absolutely a game changer for me.)

I don't have the service running atm but I believe it autodirects to https.

Let me know how it goes, good luck.
