### ISSUE TITLE
Cannot connect to DB during install

### ISSUE THREAD

**Issue by jursed** [projectsend/projectsend#719]
I have installed ProjectSend and have gotten as far as the `make-config.php` install page.

**No matter what I do, I cannot get past the "check" phase. I get four red warning icons next to the "host", "database name", "username" and "password" fields and cannot continue.**

I also tried to manually set the relevant variables in `sys.config.php`, to no avail. After I've done that, all (valid) ProjectSend URLs just return empty files.

I have ProjectSend in a Docker container (custom installation, but exactly as per the official instructions). The MySQL database is in another container, but is perfectly accessible from within the ProjectSend container with the given credentials (i.e. through the regular MySQL console). I also tried using the IP address instead of the hostname - no difference.

I've also set `DEBUG` to True in `sys.vars.php`, and have set up explicit PHP error logging to `/var/log/php/`, but no file gets created. I have no idea where to find any trace of what is actually wrong.

I've also tried [the LinuxServer Docker image](https://hub.docker.com/r/linuxserver/projectsend/), with the same results.

I have the same symptoms as issues #715 and #648. Neither received any attention.

### Environment

* ProjectSend version: r1070
* php version: 7.2.19-0ubuntu0.18.04.1
* MySQL version: 8.0.16
* Docker base image: Ubuntu 18.04

**Comment by ignacionelson** [comment]
Hello! The problem might be on the folders permissions.
I've seen cases where this fails, but the error message is not shown on the installer, so everything seems OK but actual validation didn't pass.
Please chmod 775 to /upload, /upload/files and /cache. Let me know if that helps

**Comment by jursed** [comment]
Hello Ignacio,

thanks for the support. However, even with mode `755`, I'm still stuck. (Just for the record, the directories were already `750` before, and under `www-data:www-data` ownership, so they should have been accesible by the webserver.)

**Comment by ignacionelson** [comment]
That's weird. I still believe that the issue might come from there since it's the only part (that I know of) that might not show an error when found.
Best way would be to edit the make-config.php file and set those checks are true always, or every other check just in case you think everything is really OK.

Just replace line 134
$ready_to_go = $pdo_connected && (!$table_exists || $reuse_tables) && $lang_ok && $config_file_writable && $upload_files_dir_writable && $cache_dir_writable;

with

$ready_to_go = $pdo_connected && (!$table_exists || $reuse_tables);

or even

$ready_to_go = true;

**Comment by jursed** [comment]
`sys.config.php` got written correctly (after setting `$ready_to_go = true;`), but I get to the same point as when I created that config file manually. Install page says "the configuration file already exists" and any other URL returns HTTP status 500.

Speaking of which, the 500 status is obviously wrong, but even with debug logging enabled both in Apache and `php.ini`, i can't find any stack traces or any errors related to what went wrong.

**Comment by jursed** [comment]
No idea what went wrong, but I ran out of time and had to switch to a different project. I guess it was a fluke, quite possibly unrelated to ProjectSend code itself. Anyway, thanks for the support.

**Comment by ignacionelson** [comment]
Sorry to hear that :(
Thank you for trying to get PS to work and your interest on it!

**Comment by Dennisreneholm** [comment]
I got the same error.
Using docker container with linuxserver. Exact same error.

**Comment by cmullins83** [comment]
Same as Dennisreneholm. Using linuxserver's image.

**Comment by joseon-penggwin** [comment]
May 2020, I get the same error. Can not get it to work at all. Tips and Help appreciated.

**Comment by jellevdbos** [comment]
I found a solution. You should use native password authentication in your MySql database. In Mysql 5.x this was default, since mysql 8.x it is not. You can find more info here https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

**Comment by M-Gregoire** [comment]
> I found a solution. You should use native password authentication in your MySql database. In Mysql 5.x this was default, since mysql 8.x it is not. You can find more info here https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

Thank you! This works perfectly

**Comment by chhaugen** [comment]
It's not enough to just give it the root password. The database and users must be set.

```yaml
services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    restart: unless-stopped
    depends_on: 
      - db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - config:/config
      - /storage/projectsend:/data
    ports:
      - 6123:80
    networks:
      - default
      
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql:Z
    networks:
      - default

volumes:
  config:
  db:

networks:
  default:
```

```
PUID=1000
PGID=1000
TZ=Europe/Oslo
MARIADB_ROOT_PASSWORD=rootpassword
MARIADB_DATABASE=projectsend
MARIADB_USER=projectsend
MARIADB_PASSWORD=dbpassword
```

**Comment by Tiavor** [comment]
I have the same problem. when I look at the table mysql.user and find the login method, it's all mysql_native_password, yet I can't connect. all the folders are with user 1000:1000 and 775. I can connect with a mysql client.

update, it works now, it's a bit more complicated than just starting both container and hoping it works.
add those to the docker-compose.yml for db and projectsend (with different ips):

```
services:
#...
   networks:
      mynet123:
        ipv4_address: 172.25.0.5
networks:
  mynet123:
    external: true
    name: mynet123`
```
